version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_TYPE=postgres
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=124578pz
      - DATABASE_DATABASE=railway
      - DATABASE_PORT=5432
      - DATABASE_LOGGING=false
      - DATABASE_SSL=true
      - PORT=3000
    command: npm run start

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 124578pz
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
